### ISSUE TITLE
init routines should take retval into account

### ISSUE THREAD

**Issue by timsjostrand** [timsjostrand/lodge#1]
Currently not a lot of error checking is done in `graphics_init()` and it's subsequent calls, meaning when things start going horribly wrong there will be a lot of manual debugging.

We should decide on a standard for retrieving errors:
- return 0 on error, 1 on success.
  Pros: error checking is clean to implement `if(!graphics_init(...)) { ... }`.
  Cons: no way to distinguish between error types, rely on calling function to print something to `stderr`.
- return 0 on success, negative values on error.
  Pros: can assign all negative values to specific error codes, leaves positive values for returning file handles etc.
  Cons: error checking is not as clean ?  `if(graphics_init(...) != GRAPHICS_OK) { ... }`, have to maintain a list of error codes and their messages.

The second option is probably the best one?

**Comment by realbogart** [comment]
The only time I ever interpret 0 as an error is when a function returns a pointer to something (not zero == success).

I prefer that 0 is returned on success if the return value is an error code (Second option)

Returning 0 on error feels wrong :) (Except for when NULL checking pointers)

**Comment by timsjostrand** [comment]
Fixed in c3ad10aa99ea987bc10018115f12d617d1c79bfd.
