### ISSUE TITLE
VFS: Run callback for missing files?

### ISSUE THREAD

**Issue by timsjostrand** [timsjostrand/lodge#2]
It would be a nice quality-of-life feature if explicitly calling: `vfs_register_callback("test.png", reload_textures);` would call back `reload_textures` even if `test.png` is not present on the path (once, like ususal, but perhaps with the size argument set to 0?).

This way, you can test size==0 and add a debug statement saying the file is missing (or maybe handle it gracefully, like generating a dummy texture). Also it saves a little debugging time when you mounted the wrong directory :-)

This would obviously fail-as-intended if using `vfs_register_callback_filter()`!

**Comment by realbogart** [comment]
https://github.com/timsjostrand/glpong/commit/ee15bbd3ee9380f6c99187592aade76ad546a76d

fixed

edit: hmm but it should fire when vfs_run_callbacks is called instead...

edit2: https://github.com/timsjostrand/glpong/commit/5bfe1b6a85ab62a922f8e510e5ba0e7926d5c82a

**Comment by timsjostrand** [comment]
Cool!
