### ISSUE TITLE
runtime fullscreen

### ISSUE THREAD

**Issue by timsjostrand** [timsjostrand/lodge#22]
Add ability to change window mode in runtime, like most engines allow alt+enter to switch between fullscreen borderless and windowed mode.

Something like this http://gamedev.stackexchange.com/questions/38620/toggle-fullscreen-at-runtime

**Comment by realbogart** [comment]
added function lodge_window_set_mode

**Comment by realbogart** [comment]
also added lodge_window_toggle_fullscreen
