### ISSUE TITLE
VFS: bug on trailing slash in ASSET_PATH

### ISSUE THREAD

**Issue by timsjostrand** [timsjostrand/lodge#27]
Works as intended:
`set(ASSET_PATH "/home/tim/Dropbox/Assets/glpong-assets")`

Does not work:
`set(ASSET_PATH "/home/tim/Dropbox/Assets/glpong-assets/")`
(generated `assets.h` is missing first char in each filename)

Solutions:
1) Trailing slash is stripped in cmake
2) Proper support in vfs.c for trailing slash

**Comment by realbogart** [comment]
fixed
