### ISSUE TITLE
Semi-static asset management idea

### ISSUE THREAD

**Issue by timsjostrand** [timsjostrand/lodge#3]
We could have cmake generate a source file `assets.c`, based on the directory listings of a build variable `ASSETS_DIR`:

With `ASSETS_DIR=C:\Dropbox\glpong-assets` this directory containing "vivaldi.ogg", something like following would be generated:

``` c
const char *ASSETS_DIR = "C:\\Dropbox\\glpong-assets";

struct assets {
    struct sound_fx vivaldi; // struct sound_fx based on ".ogg" extension
    /* ... */
} assets;

void assets_reload_sound(/* ... */)
{
    /* ... */
}

void assets_load(/* resources from main.c here */)
{
    vfs_mount(ASSETS_DIR);
    vfs_register_callback("vivaldi.ogg", &assets_reload_sound, &assets.vivaldi); // reload_sound based on ".ogg" extension
    /* ... */
    vfs_run_callbacks();
}

void assets_release()
{
    sound_free(&assets.vivaldi);
}
```

(This is basically how Android apps does asset management.)

The drawback is that we are bound to cmake for generating part of the source code, the positive is that `main.c` will get _a lot_ shorter without having to manually load assets + new assets can be implemented simply by rebuilding `assets.c`.

Would probably also require something like an ignore-list where you can specify files that would _not_ be automatically loaded:

```
earl_backup.png
*.psd
```

**Comment by realbogart** [comment]
I think this is a good idea!

`The drawback is that we are bound to cmake for generating part of the source code`

We could instead have a generate_assets.c that handles source-generation, then build and call it as a pre_build step.

Some pseudo cmake code:

```
add_executable(generate_assets generate_assets.c)
add_custom_command(
    glpong 
    PRE_BUILD 
    <command for calling the compiled generate_assets>
)
```

**Comment by timsjostrand** [comment]
@realbogart On an unrelated note: it would be cool if the VFS also supported mounting archives like `.tar`.

Then we could add a build step to the Release version (Debug still uses the current directory structure for easy development) of a game where you point at an assets directory and it is compiled into, for instance, `assets.tar`. Distributing a game becomes really easy, it's just two files (an exe + its assets archive).
- If you want to patch a game, just do a binary diff of the two asset files.
- I don't know how well-supported this feature is in compilers, but in gcc you can compile a binary file into an executable and access it with a pointer in c. This would be even sweeter, essentially making the game a one file application.
- Optionally compress the assets archive for faster download times (con: slows game load time)?
- libarchive is really easy to use https://github.com/libarchive/libarchive/

**Comment by timsjostrand** [comment]
Come to think of it, maybe `.tar` and `libarchive` support is overkill.

Couldn't you just dump the `struct vfs_file file_table[MAX_NUM_FILES];` in vfs.c to a file and load that back directly to memory when starting the game? Would be super-fast?
